In [3]:
import numpy as np

# Parameters
S0 = 100           # Spot price
K = 100            # Strike price
T = 1.0            # Time to maturity (in years)
r = 0.05           # Risk-free rate (annualized)
sigma = 0.2        # Volatility (annualized)
N = 3              # Number of steps
dt = T / N         # Length of each time step

# Step 1: Calculate u (up factor), d (down factor), and p (risk-neutral probability)
u = np.exp(sigma * np.sqrt(dt))   # Up factor
d = 1 / u                         # Down factor
p = (np.exp(r * dt) - d) / (u - d)  # Risk-neutral probability
discount_factor = np.exp(-r * dt)   # Discount factor for one step

print(f"Parameters:")
print(f"u (up factor): {u:.4f}")
print(f"d (down factor): {d:.4f}")
print(f"p (risk-neutral probability): {p:.4f}")
print(f"Discount Factor: {discount_factor:.4f}\n")

# Step 2: Generate the binomial tree for stock prices
stock_price = np.zeros((N+1, N+1))  # 2D array to hold stock prices
for i in range(N+1):
    for j in range(i+1):
        stock_price[j, i] = S0 * (u ** (i - j)) * (d ** j)

print("Stock Prices at Each Node:")
print(stock_price, "\n")

# Step 3: Initialize option values as a 2D array
option_values = np.zeros((N+1, N+1))  # 2D array to store option values at all nodes
for j in range(N+1):
    option_values[j, N] = np.maximum(stock_price[j, N] - K, 0)  # Call option payoff at maturity

print("Option Values at Maturity:")
print(option_values[:, N], "\n")

# Step 4: Backward Induction to Calculate Option Value at Each Node
for i in range(N-1, -1, -1):  # Start from the second last step and move backwards
    for j in range(i+1):
        hold_value = discount_factor * (p * option_values[j, i+1] + (1 - p) * option_values[j+1, i+1])
        intrinsic_value = np.maximum(stock_price[j, i] - K, 0)  # Intrinsic value for American option
        option_values[j, i] = np.maximum(hold_value, intrinsic_value)  # American option check

print("Option Values at Each Node (Backward Induction):")
print(option_values, "\n")

# Final option price at root node
option_price = option_values[0, 0]
print(f"The American Call Option Price is: {option_price:.4f}")


Parameters:
u (up factor): 1.1224
d (down factor): 0.8909
p (risk-neutral probability): 0.5438
Discount Factor: 0.9835

Stock Prices at Each Node:
[[100.         112.24009024 125.97837858 141.39824581]
 [  0.          89.09472523 100.         112.24009024]
 [  0.           0.          79.37870064  89.09472523]
 [  0.           0.           0.          70.72223522]] 

Option Values at Maturity:
[41.39824581 12.24009024  0.          0.        ] 

Option Values at Each Node (Backward Induction):
[[11.04387109 17.71388824 27.6312332  41.39824581]
 [ 0.          3.50065379  6.54586268 12.24009024]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]] 

The American Call Option Price is: 11.0439


In [5]:
import numpy as np

# Parameters
S0 = 100           # Spot price
K = 100            # Strike price
T = 1.0            # Time to maturity (in years)
r = 0.05           # Risk-free rate (annualized)
sigma = 0.2        # Volatility (annualized)
N = 3              # Number of steps
dt = T / N         # Length of each time step

# Step 1: Calculate u (up factor), d (down factor), and p (risk-neutral probability)
u = np.exp(sigma * np.sqrt(dt))   # Up factor
d = 1 / u                         # Down factor
p = (np.exp(r * dt) - d) / (u - d)  # Risk-neutral probability
discount_factor = np.exp(-r * dt)   # Discount factor for one step

print(f"Parameters:")
print(f"u (up factor): {u:.4f}")
print(f"d (down factor): {d:.4f}")
print(f"p (risk-neutral probability): {p:.4f}")
print(f"Discount Factor: {discount_factor:.4f}\n")

# Step 2: Generate the binomial tree for stock prices
stock_price = np.zeros((N+1, N+1))  # 2D array to hold stock prices
for i in range(N+1):
    for j in range(i+1):
        stock_price[j, i] = S0 * (u ** (i - j)) * (d ** j)

print("Stock Prices at Each Node:")
print(stock_price, "\n")

# Step 3: Initialize option values as a 2D array
option_values = np.zeros((N+1, N+1))  # 2D array to store option values at all nodes
for j in range(N+1):
    option_values[j, N] = np.maximum(stock_price[j, N] - K, 0)  # Call option payoff at maturity

print("Option Values at Maturity:")
print(option_values[:, N], "\n")

# Step 4: Backward Induction to Calculate Option Value at Each Node
for i in range(N-1, -1, -1):  # Start from the second last step and move backwards
    for j in range(i+1):
        hold_value = discount_factor * (p * option_values[j, i+1] + (1 - p) * option_values[j+1, i+1])
        intrinsic_value = np.maximum(stock_price[j, i] - K, 0)  # Intrinsic value for American option
        option_values[j, i] = np.maximum(hold_value, intrinsic_value)  # American option check

print("Option Values at Each Node (Backward Induction):")
print(option_values, "\n")

# Final option price at root node
option_price = option_values[0, 0]
print(f"The American Call Option Price is: {option_price:.4f}")


Parameters:
u (up factor): 1.1224
d (down factor): 0.8909
p (risk-neutral probability): 0.5438
Discount Factor: 0.9835

Stock Prices at Each Node:
[[100.         112.24009024 125.97837858 141.39824581]
 [  0.          89.09472523 100.         112.24009024]
 [  0.           0.          79.37870064  89.09472523]
 [  0.           0.           0.          70.72223522]] 

Option Values at Maturity:
[41.39824581 12.24009024  0.          0.        ] 

Option Values at Each Node (Backward Induction):
[[11.04387109 17.71388824 27.6312332  41.39824581]
 [ 0.          3.50065379  6.54586268 12.24009024]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]] 

The American Call Option Price is: 11.0439
